### ISSUE TITLE
React native popup-menu getting stackoverflow then crashed app rn-0.50.3, rnpm-0.12.5 

### ISSUE THREAD

**Issue by munkhbaatar999** [instea/react-native-popup-menu#91]
Any solution???? I just did right. It was working perfectly. But empty TextInput focused then crashed because of popup-menu. I didn't understand why its overflowed. 

Android 4.4.2

java.lang.StackOverflowError
                                                                      at android.text.TextLine.drawTextRun(TextLine.java:1060)
                                                                       at android.text.TextLine.handleText(TextLine.java:861)
                                                                       at android.text.TextLine.handleRun(TextLine.java:1028)
                                                                       at android.text.TextLine.drawRun(TextLine.java:463)
                                                                       at android.text.TextLine.draw(TextLine.java:261)
                                                                       at android.text.Layout.drawText(Layout.java:363)
                                                                       at android.text.Layout.draw(Layout.java:220)
                                                                       at android.widget.TextView.onDraw(TextView.java:6421)
                                                                       at android.view.View.draw(View.java:15410)
                                                                       at android.view.View.getDisplayList(View.java:14301)
                                                                       at android.view.View.getDisplayList(View.java:14343)
                                                                       at android.view.View.draw(View.java:15124)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
                                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:652)
                                                                       at android.view.View.getDisplayList(View.java:14296)
                                                                       at android.view.View.getDisplayList(View.java:14343)
                                                                       at android.view.View.draw(View.java:15124)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
                                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:652)
                                                                       at android.view.View.getDisplayList(View.java:14296)
                                                                       at android.view.View.getDisplayList(View.java:14343)
                                                                       at android.view.View.draw(View.java:15124)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
                                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:652)
                                                                       at android.view.View.getDisplayList(View.java:14296)
                                                                       at android.view.View.getDisplayList(View.java:14343)
                                                                       at android.view.View.draw(View.java:15124)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
                                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:652)
                                                                       at android.view.View.draw(View.java:15413)
                                                                       at android.view.View.getDisplayList(View.java:14301)
                                                                       at android.view.View.getDisplayList(View.java:14343)
                                                                       at android.view.View.draw(View.java:15124)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
                                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:652)
                                                                       at android.view.View.getDisplayList(View.java:14296)
                                                                       at android.view.View.getDisplayList(View.java:14343)
                                                                       at android.view.View.draw(View.java:15124)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
                                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:652)
                                                                       at android.view.View.getDisplayList(View.java:14296)
                                                                       at android.view.View.getDisplayList(View.java:14343)
                                                                       at android.view.View.draw(View.java:15124)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
                                                                       at android.view.View.draw(View.java:15413)
                                                                       at android.widget.FrameLayout.draw(FrameLayout.java:472)
                                                                       at android.widget.ScrollView.draw(ScrollView.java:2184)
                                                                       at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:335)
                                                                       at android.view.View.getDisplayList(View.java:14301)
                                                                       at android.view.View.getDisplayList(View.java:14343)
                                                                       at android.view.View.draw(View.java:15124)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
                                                                       at android.view.View.draw(View.java:15413)
                                                                       at android.view.View.getDisplayList(View.java:14301)
                                                                       at android.view.View.getDisplayList(View.java:14343)
                                                                       at android.view.View.draw(View.java:15124)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
                                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:652)
                                                                       at android.view.View.draw(View.java:15413)
                                                                       at android.view.View.getDisplayList(View.java:14301)
                                                                   	at android.view.View.get

**Comment by sodik82** [comment]
hi... that's strange, native exception as we don't have any native code.

> It was working perfectly.

when it was working perfectly? in older version? what TextInput - we don't use any. can you give us more details?

**Comment by munkhbaatar999** [comment]
Sorry about that. I'am working lately then figured out what happened in my code. This happened because onRefresh props of FlatList component. This issue CLOSED.

**Comment by parth3724** [comment]
@munkhbaatar999 ,
I am facing similar issue, but cannot find the cause.
Can you elaborate more on what was the issue for you ?
For me this issue occurs only in android OS 4.4.2 and 4.4.4.
